#!/usr/bin/env python3
"""Sales-ready HTML portal for multi-CCAA demo (generated by build_demo_multi_ccaa)."""

from __future__ import annotations

import html as html_lib
import json
import re
from typing import Any


def _esc(s: Any) -> str:
    if s is None:
        return ""
    return html_lib.escape(str(s), quote=True)


def _safe_href(href: str | None) -> str | None:
    if not href:
        return None
    h = str(href).strip().replace("\\", "/")
    if (
        not h
        or h.startswith("/")
        or "://" in h
        or h.lower().startswith("javascript:")
        or h.startswith("//")
    ):
        return None
    if len(h) >= 2 and h[1] == ":":
        return None
    return h


def _verdict_class(verdict: str) -> str:
    u = (verdict or "").upper().strip()
    if not u or u in {"—", "-", "N/A"}:
        return "muted"
    if "NO_GO" in u or "PENDING" in u or "FAIL" in u or "ABSTAIN" in u:
        return "bad"
    if "PARTIAL" in u or "HOLD" in u:
        return "warn"
    if u == "GO" or u.startswith("GO_") or u.startswith("GO "):
        return "ok"
    if re.search(r"(?:^|[^A-Z])GO(?:[^A-Z]|$)", u) and "GOLD" not in u:
        return "ok"
    if "GRADE A" in u or "OPS GOLD" in u:
        return "ok"
    return "muted"


def _fmt_ha(v: Any) -> str:
    if v is None:
        return "—"
    try:
        f = float(v)
    except (TypeError, ValueError):
        return "—"
    return f"{f:.0f}" if f >= 100 else f"{f:g}"


def _fmt_vp(v: Any) -> str:
    if v is None:
        return "—"
    try:
        return f"{float(v):g}"
    except (TypeError, ValueError):
        return "—"


def _gate_cell(st: str) -> str:
    raw = st if st is not None else "—"
    u = str(raw).upper().strip()
    cls = "g-skip"
    if u == "PASS":
        cls = "g-pass"
    elif u == "FAIL":
        cls = "g-fail"
    elif u == "SKIP" or u.startswith("N/A") or u in {"—", "-", "N/A"}:
        cls = "g-skip"
    return f'<td class="{cls}">{_esc(raw if raw is not None else "—")}</td>'


def render_portal(
    *,
    sites: list[dict[str, Any]],
    manifest: dict[str, Any],
    kpi: dict[str, Any],
    compare: dict[str, Any],
    scoreboard: list[dict[str, Any]],
    ha_chart_svg: str,
    perimeter_js: dict[str, Any],
    version: str = "2.1.0",
    gates_chart_svg: str = "",
    timeline_chart_svg: str = "",
    decision_cards: list[dict[str, Any]] | None = None,
    la_mierla: dict[str, Any] | None = None,
    git_short: str | None = None,
) -> str:
    by_id = {s["id"]: s for s in sites}
    for req in ("tobarra", "nijar", "camino"):
        if req not in by_id:
            raise ValueError(f"missing site {req}")

    tb, nj, cm = by_id["tobarra"], by_id["nijar"], by_id["camino"]
    built = _esc(manifest.get("built_at_utc") or "")
    honesty = manifest.get("honesty") or {}
    any_vp = bool(honesty.get("any_vp_invented"))
    decision_cards = (
        decision_cards if decision_cards is not None else (manifest.get("decision_cards") or [])
    )
    la_mierla = la_mierla if la_mierla is not None else manifest.get("la_mierla")
    git_short = git_short if git_short is not None else manifest.get("git_short")
    provenance = manifest.get("provenance") or {}
    git_label = _esc(git_short or "n/a")

    # KPI strip
    kpi_cells = []
    for k in kpi.get("kpis") or []:
        kpi_cells.append(
            f"""<div class="kpi" data-i18n-label="{_esc(k.get("id"))}">
  <div class="kpi-val">{_esc(k.get("value"))}{_esc(k.get("unit") or "")}</div>
  <div class="kpi-lbl" data-es="{_esc(k.get("label"))}" data-en="{_esc(k.get("label_en") or k.get("label"))}">{_esc(k.get("label"))}</div>
  <div class="kpi-hint">{_esc(k.get("hint"))}</div>
</div>"""
        )

    def gate_chips(s: dict[str, Any]) -> str:
        g = s.get("gates") or {}
        if not g and s.get("track") == "OPS":
            g = {
                "ANCLA": "PASS" if s.get("status_anchor") == "confirmed" else "SKIP",
                "LWIR": "PASS" if s.get("lwir") else "SKIP",
                "NO_FALSE_DISPATCH": "PASS",
            }
        chips = []
        for name, st in list(g.items())[:8]:
            cls = _verdict_class(str(st) if st != "PASS" else "GO")
            if st == "PASS":
                cls = "ok"
            elif st == "SKIP":
                cls = "muted"
            elif st == "FAIL":
                cls = "bad"
            chips.append(f'<span class="chip {cls}">{_esc(name)}:{_esc(st)}</span>')
        return "".join(chips) or '<span class="chip muted">sin scorecard</span>'

    def card(s: dict[str, Any]) -> str:
        kn = s.get("key_numbers") or {}
        metrics = s.get("metrics") or {}
        bits = []
        if kn.get("vp_m_min") is not None:
            bits.append(
                f"<div class='metric'><span class='m-val'>{_esc(_fmt_vp(kn.get('vp_m_min')))}</span>"
                f"<span class='m-lbl'>Vp m/min</span></div>"
            )
        if kn.get("area_ha") is not None:
            bits.append(
                f"<div class='metric'><span class='m-val'>{_esc(_fmt_ha(kn.get('area_ha')))}</span>"
                f"<span class='m-lbl'>ha</span></div>"
            )
        if metrics.get("n_firms_hotspots"):
            bits.append(
                f"<div class='metric'><span class='m-val'>{_esc(metrics.get('n_firms_hotspots'))}</span>"
                f"<span class='m-lbl'>FIRMS</span></div>"
            )
        if metrics.get("hausdorff_m") is not None:
            bits.append(
                f"<div class='metric'><span class='m-val' style='font-size:1.1rem'>{_esc(metrics.get('hausdorff_m'))}</span>"
                f"<span class='m-lbl'>Hausdorff m</span></div>"
            )
        if s["id"] == "camino":
            fd, fe = kn.get("fecha_det"), kn.get("fecha_ext")
            if fd or fe:
                bits.append(
                    f"<div class='metric'><span class='m-val' style='font-size:.95rem'>{_esc(fd or '—')}</span>"
                    f"<span class='m-lbl'>det→{_esc(fe or '—')}</span></div>"
                )
        metrics_html = (
            "".join(bits)
            or "<div class='metric'><span class='m-val'>—</span><span class='m-lbl'>n/a</span></div>"
        )

        links = s.get("links") or {}
        btns = []

        def add(key: str, label: str, primary: bool = False) -> None:
            href = _safe_href(links.get(key))
            if href:
                cls = "btn primary" if primary else "btn"
                btns.append(
                    f"<a class='{cls}' href='{_esc(href)}' target='_blank' rel='noopener'>{_esc(label)}</a>"
                )

        add("map", "Mapa full", True)
        add("fig_ros", "Fig. ROS", True)
        add("fig_area", "Fig. área")
        add("brief", "Brief")
        add("scorecard", "Scorecard")
        add("acta", "Acta")
        add("temporal", "Temporal")
        add("anchor", "Ancla")
        if not btns:
            btns.append("<span class='btn disabled'>SKIP</span>")

        sid = _esc(s.get("id"))
        map_div = f'<div class="mini-map" id="map-{sid}" data-site="{sid}"></div>'
        figs = ""
        fr = _safe_href(links.get("fig_ros"))
        fa = _safe_href(links.get("fig_area"))
        if fr or fa:
            parts = []
            if fr:
                parts.append(
                    f"<a href='{_esc(fr)}' target='_blank'><img src='{_esc(fr)}' alt='ROS Tobarra' loading='lazy'/></a>"
                )
            if fa:
                parts.append(
                    f"<a href='{_esc(fa)}' target='_blank'><img src='{_esc(fa)}' alt='Área Tobarra' loading='lazy'/></a>"
                )
            figs = f"<div class='fig-row'>{''.join(parts)}</div>"

        return f"""
<article class="site-card" id="card-{sid}" data-panel="{_esc(s.get("panel"))}" data-track="{_esc(s.get("track"))}">
  <header class="card-head">
    <div>
      <span class="track track-{"ops" if s.get("track") == "OPS" else "open"}">{_esc(s.get("track_label"))}</span>
      <h2>{_esc(s.get("name_display"))}</h2>
      <p class="ccaa">{_esc(s.get("ccaa"))} · {_esc(s.get("year_label"))}</p>
    </div>
    <div class="verdicts">
      <span class="pill {_verdict_class(str(s.get("verdict")))}">{_esc(s.get("verdict"))}</span>
      <span class="pill {_verdict_class(str(s.get("decision_open")))}">decisión: {_esc(s.get("decision_open"))}</span>
    </div>
  </header>
  <p class="headline">{_esc(s.get("headline"))}</p>
  <div class="metrics">{metrics_html}</div>
  <div class="chips">{gate_chips(s)}</div>
  {map_div}
  {figs}
  <dl class="meta">
    <div><dt data-es="Fuente" data-en="Source">Fuente</dt><dd>{_esc(s.get("source"))}</dd></div>
    <div><dt data-es="Demuestra" data-en="Shows">Demuestra</dt><dd>{_esc(s.get("what_shows"))}</dd></div>
    <div><dt data-es="No dice" data-en="Does not claim">No dice</dt><dd>{_esc(s.get("what_not"))}</dd></div>
  </dl>
  <p class="attr">{_esc(s.get("attribution"))}</p>
  <div class="actions">{"".join(btns)}</div>
</article>"""

    cards = "\n".join(card(s) for s in sites)

    # Scoreboard
    sb_rows = []
    for r in scoreboard:
        sb_rows.append(
            "<tr>"
            f"<td>{_esc(r.get('name'))}</td>"
            + _gate_cell(str(r.get("O2")))
            + _gate_cell(str(r.get("HAUSDORFF")))
            + _gate_cell(str(r.get("FIRMS")))
            + _gate_cell(str(r.get("DNBR")))
            + _gate_cell(str(r.get("NO_FALSE_DISPATCH")))
            + _gate_cell(str(r.get("PROVENANCE")))
            + f"<td class='{_verdict_class(str(r.get('verdict')))}'>{_esc(r.get('verdict'))}</td>"
            + "</tr>"
        )

    # Compare
    cmp_rows = []
    for r in compare.get("rows") or []:
        cmp_rows.append(
            f"""<tr>
  <td>{_esc(r.get("name"))}</td>
  <td>{_esc(r.get("ccaa"))}</td>
  <td>{_esc(r.get("track"))}</td>
  <td>{_esc(_fmt_ha(r.get("area_ha")))}</td>
  <td>{_esc(_fmt_vp(r.get("vp_m_min")))}</td>
  <td>{"sí" if r.get("lwir") else "no"}</td>
  <td class="{_verdict_class(str(r.get("decision")))}">{_esc(r.get("decision"))}</td>
  <td>{_esc(r.get("verdict"))}</td>
  <td class="src">{_esc(r.get("source"))}</td>
</tr>"""
        )

    silver = manifest.get("silver_packs") or []
    silver_html = ""
    if silver:
        lis = "".join(
            f"<li><strong>{_esc(x.get('name'))}</strong> · {_esc(_fmt_ha(x.get('area_ha')))} ha · "
            f"<a href='{_esc(_safe_href(x.get('map')) or '#')}' target='_blank'>mapa</a></li>"
            for x in silver
        )
        silver_html = f"<ul class='silver-list'>{lis}</ul>"

    # Decision cards
    dc_html_parts = []
    for dc in decision_cards:
        st = str(dc.get("status") or "OK")
        if st == "SKIP" and dc.get("id") == "none":
            dc_html_parts.append(
                "<div class='dc-card skip'><p class='muted'><b>Decision Card:</b> SKIP — "
                "no se encontró fire_decision_card en gold_e2e / docs / forensic_demo.</p></div>"
            )
            continue
        reasons = dc.get("reasons") or []
        r_lis = "".join(f"<li>{_esc(r)}</li>" for r in reasons[:6]) or "<li class='muted'>—</li>"
        disclaimers = dc.get("disclaimers") or []
        if not disclaimers:
            # Always surface anti-dispatch honesty next to GO/HOLD
            disclaimers = ["Not a tactical dispatch order."]
        d_lis = "".join(f"<li>{_esc(d)}</li>" for d in disclaimers[:6])
        href = _safe_href(dc.get("href"))
        link = (
            f"<a class='btn ghost' href='{_esc(href)}' target='_blank' rel='noopener'>JSON</a>"
            if href
            else ""
        )
        conf = dc.get("confidence_pred_label") or dc.get("confidence_pred")
        kind = str(dc.get("kind") or "live")
        is_sample = kind == "schema_sample"
        rel_pass = dc.get("system_reliability_pass")
        rel_false = rel_pass is False
        dec_cls = _verdict_class(str(dc.get("decision")))
        # GO without reliability gate green → warn, not "tactical green"
        if rel_false and dec_cls == "ok":
            dec_cls = "warn"
        sample_badge = (
            '<span class="pill muted">SAMPLE SCHEMA (not field decide)</span>' if is_sample else ""
        )
        rel_banner = ""
        if rel_false:
            rel_banner = (
                "<p class='dc-rel-warn' role='status'>"
                "<strong>Reliability gate not green</strong> — "
                "system_reliability_pass=false · <em>not a tactical GO</em>."
                "</p>"
            )
        elif rel_pass is True:
            rel_banner = (
                "<p class='muted' style='margin:.35rem 0;font-size:.82rem'>"
                "reliability_pass=true</p>"
            )
        card_cls = "dc-card sample" if is_sample else "dc-card"
        if rel_false:
            card_cls += " rel-fail"
        dc_html_parts.append(
            f"""<div class="{card_cls}">
  <div class="dc-head">
    <span class="pill {dec_cls}">{_esc(dc.get("decision"))}</span>
    {sample_badge}
    <strong>{_esc(dc.get("label") or dc.get("id"))}</strong>
    <span class="muted">{_esc(dc.get("event_id") or "")}</span>
  </div>
  <p class="muted" style="margin:.35rem 0;font-size:.82rem">conf {_esc(conf)} · reliability_pass={_esc(rel_pass)}</p>
  {rel_banner}
  <p class="dc-disc-label">Disclaimers</p>
  <ul class="dc-disclaimers">{d_lis}</ul>
  <ul class="dc-reasons">{r_lis}</ul>
  {link}
</div>"""
        )
    decision_html = "".join(dc_html_parts) or "<p class='muted'>SKIP decision cards</p>"

    # La Mierla optional
    la_html = ""
    if la_mierla:
        lm_links = la_mierla.get("links") or {}
        lm_btns = []
        for key, lab in (("map", "Mapa"), ("brief", "Brief"), ("decision_card", "Decision card")):
            href = _safe_href(lm_links.get(key))
            if href:
                lm_btns.append(
                    f"<a class='btn' href='{_esc(href)}' target='_blank' rel='noopener'>{_esc(lab)}</a>"
                )
        blocked = la_mierla.get("blocked") or []
        blk = ", ".join(_esc(b) for b in blocked) if blocked else "—"
        la_html = f"""
<article class="site-card optional-card" id="card-la_mierla" data-panel="la_mierla" data-optional="1">
  <header class="card-head">
    <div>
      <span class="track track-open">{_esc(la_mierla.get("track_label"))}</span>
      <h2>{_esc(la_mierla.get("name_display"))}</h2>
      <p class="ccaa">{_esc(la_mierla.get("ccaa"))} · {_esc(la_mierla.get("year_label"))}</p>
    </div>
    <div class="verdicts">
      <span class="pill {_verdict_class(str(la_mierla.get("verdict")))}">{_esc(la_mierla.get("verdict"))}</span>
      <span class="pill {_verdict_class(str(la_mierla.get("decision_open")))}">decisión: {_esc(la_mierla.get("decision_open"))}</span>
    </div>
  </header>
  <p class="headline">{_esc(la_mierla.get("headline"))}</p>
  <p class="muted" style="font-size:.8rem">Blocked: {blk} · no diluye el pitch de 3 sitios</p>
  <p class="attr">{_esc(la_mierla.get("attribution"))}</p>
  <div class="actions">{"".join(lm_btns) or "<span class='btn disabled'>SKIP</span>"}</div>
</article>"""

    # Provenance
    prov_sources = provenance.get("sources") or []
    if not prov_sources:
        prov_sources = [
            {"label": "INFOCAM", "contact": "data/infocam_anchors.json", "role": "Anclas OPS"},
            {
                "label": "REDIAM",
                "contact": "rediam.atiende.csma@juntadeandalucia.es",
                "role": "O2 AND",
            },
            {"label": "RAI/INFOEX", "contact": "rai@juntaex.es", "role": "O2 EXT"},
        ]
    prov_rows = "".join(
        f"<tr><td>{_esc(p.get('label'))}</td><td class='src'>{_esc(p.get('contact'))}</td>"
        f"<td>{_esc(p.get('role'))}</td></tr>"
        for p in prov_sources
    )

    camino_days = (cm.get("key_numbers") or {}).get("duration_days")
    days_note = (
        f" · duración det→ext: <b>{_esc(camino_days)} días</b>" if camino_days is not None else ""
    )

    tb_confirmed = tb.get("status_anchor") == "confirmed"
    vp_tb = _fmt_vp((tb.get("key_numbers") or {}).get("vp_m_min"))
    ha_tb = _fmt_ha((tb.get("key_numbers") or {}).get("area_ha"))
    ha_nj = _fmt_ha((nj.get("key_numbers") or {}).get("area_ha"))
    ha_cm = _fmt_ha((cm.get("key_numbers") or {}).get("area_ha"))
    if tb_confirmed:
        tb_guion = f"ancla INFOCAM Vp ≈ {vp_tb} m/min · ≈ {ha_tb} ha confirmed"
    else:
        tb_guion = f"ancla status {_esc(tb.get('status_anchor') or 'SKIP')} (Vp no publicados)"

    banner = ""
    if any_vp:
        banner = (
            "<div class='honesty-banner' role='alert'><strong>INTEGRITY FAIL:</strong> "
            "vp_invented=true en algún pack. No usar para claims de sala.</div>"
        )

    perim_json = json.dumps(perimeter_js, ensure_ascii=False, separators=(",", ":"))
    # prevent </script> breakout
    perim_json = perim_json.replace("</", "<\\/")

    i18n = {
        "hero_title": {
            "es": "Decision support multi-CCAA: térmico validado donde hay datos, perímetro oficial donde hay Junta, abstención cuando no se puede mentir.",
            "en": "Multi-region decision support: validated thermal where data exists, official perimeters where agencies share them, abstention when we cannot invent.",
        },
        "hero_sub": {
            "es": "No vendemos mapitas gratis. Vendemos <b>GO / HOLD / ABSTAIN</b>, audit trail y prueba multi-CCAA con los mismos gates.",
            "en": "We do not sell free maps. We sell <b>GO / HOLD / ABSTAIN</b>, audit trail, and multi-region proof with the same gates.",
        },
        "cta_demo": {"es": "Ver guion 12 min", "en": "12-min demo script"},
        "cta_anchor": {"es": "Pedir ancla Vp/ha", "en": "Request Vp/ha anchor"},
    }
    # neutralize </script> breakout (no backslash inside f-string expr)
    i18n_json = json.dumps(i18n, ensure_ascii=False).replace("</", "<" + "\\/")

    return f"""<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>WFD · Demo multi-CCAA vendible — Tobarra · Níjar · Caminomorisco</title>
<meta name="description" content="Producto demo: OPS gold CLM + O2 REDIAM + O2 RAI. KPIs, scoreboard, mapas, guion 12 min, pitch. HOLD sin inventar Vp."/>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
:root {{
  --bg:#070b12; --card:#111925; --card-hi:#152032; --line:rgba(100,140,190,.22);
  --text:#e8eef8; --muted:#8b9bb4; --accent:#3b9eff; --cyan:#2fd4c8; --ops:#f0a030;
  --ok:#1ecf8c; --warn:#f0b429; --bad:#ff5c6c; --radius:14px;
  --font:"Segoe UI",system-ui,-apple-system,sans-serif;
}}
*{{box-sizing:border-box}}
html{{scroll-behavior:smooth}}
body{{margin:0;font-family:var(--font);background:var(--bg);color:var(--text);line-height:1.5;min-height:100vh}}
a{{color:#7ec8ff;text-decoration:none}} a:hover{{text-decoration:underline}}
.bg-fx{{position:fixed;inset:0;z-index:0;pointer-events:none;background:
  radial-gradient(ellipse 70% 45% at 15% -5%,rgba(45,100,180,.28),transparent 55%),
  radial-gradient(ellipse 50% 35% at 90% 15%,rgba(200,80,40,.12),transparent 50%),
  linear-gradient(180deg,#080d16,#070b12)}}
.wrap{{position:relative;z-index:1;max-width:1180px;margin:0 auto;padding:0 1.15rem 3rem}}
.topnav{{position:sticky;top:0;z-index:50;backdrop-filter:blur(12px);background:rgba(7,11,18,.88);
  display:flex;align-items:center;justify-content:space-between;gap:.75rem;flex-wrap:wrap;
  padding:.75rem 0;border-bottom:1px solid var(--line);margin-bottom:1rem}}
.brand{{display:flex;align-items:center;gap:.65rem}}
.brand-mark{{width:34px;height:34px;border-radius:10px;background:conic-gradient(from 200deg,var(--cyan),var(--accent),var(--ops),var(--cyan))}}
.brand h1{{margin:0;font-size:.95rem;letter-spacing:.1em;font-weight:800}}
.brand .sub{{color:var(--muted);font-size:.7rem}}
.nav-links{{display:flex;gap:.3rem;flex-wrap:wrap}}
.nav-links a{{font-size:.7rem;font-weight:650;padding:.3rem .55rem;border-radius:999px;border:1px solid var(--line);color:var(--muted)}}
.nav-links a:hover{{color:var(--text);border-color:rgba(59,158,255,.45);text-decoration:none}}
.lang-btn,.mode-btn{{font-size:.7rem;font-weight:700;padding:.3rem .55rem;border-radius:8px;border:1px solid var(--line);
  background:var(--card-hi);color:var(--text);cursor:pointer}}
.hero{{padding:1.25rem 0 1rem}}
.hero .eyebrow{{color:var(--cyan);font-size:.72rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}}
.hero h2{{margin:.4rem 0 .7rem;font-size:clamp(1.25rem,2.8vw,1.75rem);font-weight:750;max-width:46rem;letter-spacing:-.02em}}
.hero .pitch{{color:var(--muted);max-width:48rem;margin:0 0 1rem}}
.hero .pitch b{{color:var(--text)}}
.cta-row{{display:flex;flex-wrap:wrap;gap:.5rem;margin-bottom:1rem}}
.btn{{display:inline-block;font-size:.8rem;font-weight:650;padding:.45rem .8rem;border-radius:8px;
  border:1px solid var(--line);background:var(--card-hi);color:var(--text);cursor:pointer;text-decoration:none!important}}
.btn.primary{{background:linear-gradient(135deg,#1a4a8a,#1e6fd4);border-color:rgba(59,158,255,.5);color:#fff}}
.btn.ghost{{background:transparent;color:var(--muted)}}
.btn.ops{{background:rgba(240,160,48,.15);border-color:rgba(240,160,48,.4);color:var(--ops)}}
.kpi-strip{{display:grid;grid-template-columns:repeat(4,1fr);gap:.65rem;margin:1rem 0 1.25rem}}
@media(max-width:900px){{.kpi-strip{{grid-template-columns:repeat(2,1fr)}}}}
@media(max-width:480px){{.kpi-strip{{grid-template-columns:1fr}}}}
.kpi{{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);padding:.75rem .9rem}}
.kpi-val{{font-size:1.35rem;font-weight:800;font-variant-numeric:tabular-nums;letter-spacing:-.02em}}
.kpi-lbl{{font-size:.72rem;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-top:.15rem}}
.kpi-hint{{font-size:.7rem;color:var(--muted);opacity:.85;margin-top:.15rem}}
.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:1rem 0}}
@media(max-width:960px){{.cards{{grid-template-columns:1fr}}}}
.site-card{{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:1.1rem;display:flex;flex-direction:column;gap:.55rem}}
.site-card.highlight{{border-color:rgba(47,212,200,.55);box-shadow:0 0 0 1px rgba(47,212,200,.2)}}
.site-card.dim{{opacity:.45;filter:grayscale(.3)}}
.card-head{{display:flex;justify-content:space-between;gap:.5rem}}
.card-head h2{{margin:.3rem 0 0;font-size:1.3rem}}
.ccaa{{margin:0;color:var(--muted);font-size:.82rem}}
.track{{display:inline-block;font-size:.65rem;font-weight:700;letter-spacing:.05em;padding:.15rem .45rem;border-radius:6px;text-transform:uppercase}}
.track-ops{{background:rgba(240,160,48,.15);color:var(--ops);border:1px solid rgba(240,160,48,.35)}}
.track-open{{background:rgba(47,212,200,.1);color:var(--cyan);border:1px solid rgba(47,212,200,.3)}}
.pill{{display:inline-block;font-size:.65rem;font-weight:700;padding:.18rem .45rem;border-radius:999px;border:1px solid var(--line);margin-bottom:.2rem}}
.pill.ok{{color:var(--ok);border-color:rgba(30,207,140,.4)}}
.pill.warn{{color:var(--warn);border-color:rgba(240,180,41,.4)}}
.pill.bad{{color:var(--bad);border-color:rgba(255,92,108,.4)}}
.pill.muted{{color:var(--muted)}}
.verdicts{{display:flex;flex-direction:column;align-items:flex-end}}
.headline{{margin:0;font-weight:650;font-size:.95rem}}
.metrics{{display:flex;flex-wrap:wrap;gap:.55rem;padding:.5rem 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}}
.m-val{{display:block;font-size:1.35rem;font-weight:750;font-variant-numeric:tabular-nums}}
.m-lbl{{font-size:.68rem;color:var(--muted);text-transform:uppercase}}
.chips{{display:flex;flex-wrap:wrap;gap:.3rem}}
.chip{{font-size:.62rem;font-weight:650;padding:.15rem .4rem;border-radius:6px;border:1px solid var(--line);color:var(--muted)}}
.chip.ok{{color:var(--ok);border-color:rgba(30,207,140,.35)}}
.chip.bad{{color:var(--bad)}}
.chip.muted{{opacity:.8}}
.mini-map{{height:160px;border-radius:10px;border:1px solid var(--line);background:#0a1018}}
.fig-row{{display:grid;grid-template-columns:1fr 1fr;gap:.4rem}}
.fig-row img{{width:100%;border-radius:8px;border:1px solid var(--line)}}
.meta{{margin:0;font-size:.8rem}} .meta dt{{color:var(--muted);font-size:.68rem;text-transform:uppercase;margin:0}}
.meta dd{{margin:0 0 .35rem}}
.attr{{margin:0;font-size:.72rem;color:var(--muted);font-style:italic}}
.actions{{display:flex;flex-wrap:wrap;gap:.35rem;margin-top:auto}}
section.block{{background:var(--card);border:1px solid var(--line);border-radius:16px;margin:1.1rem 0;overflow:hidden}}
section.block > .sec-head{{display:flex;justify-content:space-between;align-items:center;padding:.9rem 1.1rem;cursor:pointer}}
section.block > .sec-head h3{{margin:0;font-size:.88rem;letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}}
section.block > .sec-body{{display:none;padding:0 1.1rem 1.1rem}}
section.block.open > .sec-body{{display:block}}
table.grid{{width:100%;border-collapse:collapse;font-size:.8rem}}
table.grid th,table.grid td{{border-bottom:1px solid var(--line);padding:.45rem .4rem;text-align:left}}
table.grid th{{color:var(--muted);font-size:.68rem;text-transform:uppercase}}
.g-pass{{color:var(--ok);font-weight:700}} .g-fail{{color:var(--bad);font-weight:700}} .g-skip{{color:var(--muted)}}
.chart-box{{background:rgba(0,0,0,.25);border-radius:12px;padding:.75rem;border:1px solid var(--line)}}
.guion-step{{padding:.65rem .8rem;border-left:3px solid var(--line);margin:.4rem 0;background:rgba(0,0,0,.2);border-radius:0 8px 8px 0}}
.guion-step.active{{border-left-color:var(--cyan);background:rgba(47,212,200,.08)}}
.guion-controls{{display:flex;gap:.4rem;flex-wrap:wrap;margin:.6rem 0}}
.whatif{{display:flex;align-items:center;gap:.6rem;padding:.7rem .9rem;background:rgba(240,160,48,.08);border:1px solid rgba(240,160,48,.3);border-radius:10px;margin:.5rem 0}}
.cta-box{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:.65rem}}
.cta-card{{padding:1rem;border:1px solid var(--line);border-radius:12px;background:var(--card-hi)}}
.cta-card h4{{margin:0 0 .35rem;font-size:.95rem}}
.cta-card p{{margin:0 0 .6rem;font-size:.82rem;color:var(--muted)}}
.footer{{margin-top:2rem;padding-top:1rem;border-top:1px solid var(--line);color:var(--muted);font-size:.75rem}}
.honesty-banner{{margin:.75rem 0;padding:.85rem 1rem;border-radius:12px;background:rgba(255,92,108,.12);border:1px solid rgba(255,92,108,.5);color:#ffb4bc}}
.muted{{color:var(--muted)}}
body.mode-pitch .block:not(.pitch-keep){{display:none}}
body.mode-guion #sec-guion{{display:block}}
body.mode-guion #sec-guion.open > .sec-body{{display:block}}
.silver-list{{margin:.4rem 0 0;padding-left:1.1rem;font-size:.85rem;color:var(--muted)}}
.dc-card{{background:rgba(0,0,0,.25);border:1px solid var(--line);border-radius:12px;padding:.85rem;margin:.5rem 0}}
.dc-card.skip{{border-style:dashed}}
.dc-card.sample{{opacity:.88;border-style:dashed}}
.dc-card.rel-fail{{border-color:rgba(240,180,41,.45)}}
.dc-head{{display:flex;flex-wrap:wrap;gap:.5rem;align-items:center}}
.dc-reasons{{margin:.35rem 0 0;padding-left:1.1rem;font-size:.8rem;color:var(--muted)}}
.dc-disclaimers{{margin:.25rem 0 .4rem;padding-left:1.1rem;font-size:.82rem;color:var(--warn)}}
.dc-disc-label{{margin:.4rem 0 0;font-size:.68rem;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}}
.dc-rel-warn{{margin:.4rem 0;padding:.5rem .65rem;border-radius:8px;background:rgba(240,180,41,.12);
  border:1px solid rgba(240,180,41,.4);color:var(--warn);font-size:.82rem}}
.charts-grid{{display:grid;grid-template-columns:1fr;gap:.75rem}}
@media(min-width:800px){{.charts-grid{{grid-template-columns:1fr 1fr}}}}
.optional-card{{border-style:dashed;opacity:.95}}
.skip-to{{position:absolute;left:-9999px;top:auto;width:1px;height:1px;overflow:hidden}}
.skip-to:focus{{position:static;width:auto;height:auto;padding:.4rem .7rem;background:var(--accent);color:#fff;border-radius:8px;z-index:100}}
:focus-visible{{outline:2px solid var(--cyan);outline-offset:2px}}
a:focus-visible,button:focus-visible,.btn:focus-visible,.nav-links a:focus-visible{{outline:2px solid var(--cyan);outline-offset:2px}}
.sr-only{{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0}}
.kbd-hint{{font-size:.68rem;color:var(--muted);margin:.25rem 0}}
@media print {{
  .bg-fx,.topnav .nav-links,.guion-controls,.lang-btn,.mode-btn,.mini-map,
  .whatif,.skip-to,.kbd-hint,#sec-silver,#sec-open-more{{display:none!important}}
  body{{background:#fff;color:#111;font-size:10.5pt}}
  .wrap{{max-width:100%;padding:.5rem}}
  .site-card,.block,.kpi,.cta-card{{break-inside:avoid;border-color:#ccc;background:#fff;color:#111;box-shadow:none}}
  .hero h2{{font-size:1.2rem;color:#111}}
  .hero .pitch,.muted,.attr,.kpi-hint,.ccaa{{color:#333}}
  a{{color:#06c}}
  .pill.ok,.g-pass{{color:#060}}
  .pill.warn{{color:#860}}
  .brand-mark{{display:none}}
  #pitch,#sell,.pitch-keep{{display:block!important}}
  section.block > .sec-body{{display:block!important}}
  .footer{{color:#444;font-size:.7rem}}
}}
@media (prefers-reduced-motion:reduce){{
  html{{scroll-behavior:auto}}
  *{{animation:none!important;transition:none!important}}
}}
</style>
</head>
<body data-version="{_esc(version)}" data-git="{git_label}">
<a class="skip-to" href="#main">Saltar al contenido</a>
<div class="bg-fx" aria-hidden="true"></div>
<div class="wrap">
  <nav class="topnav" aria-label="Demo" role="navigation">
    <div class="brand">
      <div class="brand-mark" aria-hidden="true"></div>
      <div>
        <h1>WFD · MULTI-CCAA</h1>
        <div class="sub">OPS gold · O2 REDIAM · O2 RAI · v{_esc(version)}</div>
      </div>
    </div>
    <div class="nav-links" id="nav-links">
      <a href="#kpis">KPIs</a>
      <a href="#sites">Sitios</a>
      <a href="#scoreboard">Gates</a>
      <a href="#compare">Comparar</a>
      <a href="#decision">Decision</a>
      <a href="#guion">Guion</a>
      <a href="#pitch">Pitch</a>
      <a href="#provenance">Provenance</a>
      <a href="#sell">CTA</a>
      <a href="#honest">Honestidad</a>
    </div>
    <div style="display:flex;gap:.35rem;align-items:center">
      <button type="button" class="mode-btn" id="btn-mode-full" data-mode="full" aria-pressed="true">Full</button>
      <button type="button" class="mode-btn" id="btn-mode-pitch" data-mode="pitch" aria-pressed="false">Pitch</button>
      <button type="button" class="mode-btn" id="btn-mode-guion" data-mode="guion" aria-pressed="false">Guion</button>
      <button type="button" class="lang-btn" id="btn-lang" title="ES/EN" aria-label="Toggle language ES EN">ES</button>
    </div>
  </nav>
  <p class="kbd-hint sr-only" id="kbd-help">Teclado: 1–3 sitios, G guion, P pitch, L idioma. Tab navega secciones.</p>
  {banner}

  <main id="main">
  <header class="hero pitch-keep" id="hero">
    <p class="eyebrow" data-es="Producto demo industrial" data-en="Industrial demo product">Producto demo industrial</p>
    <h2 id="hero-title">{_esc(i18n["hero_title"]["es"])}</h2>
    <p class="pitch" id="hero-sub">{i18n["hero_sub"]["es"]}</p>
    <div class="cta-row">
      <a class="btn primary" href="#guion" id="cta-demo">{_esc(i18n["cta_demo"]["es"])}</a>
      <a class="btn ops" href="mailto:alonso.alvbal@gmail.com?subject=WFD%20ancla%20Vp%2Fha" id="cta-anchor">{_esc(i18n["cta_anchor"]["es"])}</a>
      <a class="btn ghost" href="mailto:alonso.alvbal@gmail.com?subject=WFD%20feedback%2030min">Feedback 30 min</a>
      <button type="button" class="btn ghost" id="btn-print">Exportar pitch (print)</button>
      <a class="btn ghost" href="export/pitch_onepager.html" target="_blank" rel="noopener">One-pager HTML</a>
    </div>
    <div class="whatif">
      <input type="checkbox" id="whatif-no-anchor"/>
      <label for="whatif-no-anchor"><strong>What-if seguro:</strong> simular Tobarra <em>sin</em> ancla OPS → postura HOLD (no inventa números; solo narrativa).</label>
    </div>
  </header>

  <section id="kpis" class="pitch-keep" aria-label="KPIs" tabindex="-1">
    <div class="kpi-strip">
      {"".join(kpi_cells)}
    </div>
  </section>

  <section id="sites" class="cards pitch-keep" aria-label="Tres sitios" tabindex="-1">
    {cards}
  </section>

  <section class="block open pitch-keep" id="sec-charts">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Estadísticas · ha · gates · timeline</h3><span>▾</span></div>
    <div class="sec-body">
      <div class="charts-grid">
        <div class="chart-box">{ha_chart_svg}</div>
        <div class="chart-box">{gates_chart_svg or '<p class="muted">Sin gates chart</p>'}</div>
      </div>
      <div class="chart-box" style="margin-top:.75rem">{timeline_chart_svg or '<p class="muted">Sin timeline Camino</p>'}</div>
      <p class="muted" style="font-size:.8rem;margin:.5rem 0 0">Tobarra = ancla OPS (ha pequeñas, ROS). Níjar/Camino = ha perímetro oficial Junta. Hull FIRMS no se usa como ha quemadas.{days_note}</p>
    </div>
  </section>

  <section class="block open" id="scoreboard" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Scoreboard industrial (gates)</h3><span>▾</span></div>
    <div class="sec-body">
      <table class="grid">
        <thead><tr><th>Sitio</th><th>O2</th><th>Hausdorff</th><th>FIRMS</th><th>dNBR</th><th>No false dispatch</th><th>Provenance</th><th>Verdict</th></tr></thead>
        <tbody>{"".join(sb_rows)}</tbody>
      </table>
    </div>
  </section>

  <section class="block open" id="compare" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Comparar tracks (OPS vs OPEN O2)</h3><span>▾</span></div>
    <div class="sec-body">
      <table class="grid">
        <thead><tr><th>IF</th><th>CCAA</th><th>Track</th><th>ha</th><th>Vp</th><th>LWIR</th><th>Decisión</th><th>Verdict</th><th>Fuente</th></tr></thead>
        <tbody>{"".join(cmp_rows)}</tbody>
      </table>
      <p class="muted" style="font-size:.8rem">Cost of missing data: sin ancla OPS no hay Vp táctico; sin perímetro Junta no hay O2 oficial. El producto expone el hueco — no lo rellena con ficción.</p>
    </div>
  </section>

  <section class="block open pitch-keep" id="decision" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Decision Card viewer</h3><span>▾</span></div>
    <div class="sec-body">
      <p class="muted" style="font-size:.85rem;margin-top:0">GO / HOLD / ABSTAIN desde rutas gold/decide si existen. Soft SKIP si no hay card.</p>
      {decision_html}
    </div>
  </section>

  <section class="block" id="sec-silver">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="false"><h3>Packs silver EXT (misma tubería)</h3><span>▾</span></div>
    <div class="sec-body">{silver_html or '<p class="muted">Sin silver listados</p>'}</div>
  </section>

  <section class="block" id="sec-open-more">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="false"><h3>Más IF open (opcional · no diluye pitch)</h3><span>▾</span></div>
    <div class="sec-body">
      {la_html or '<p class="muted">La Mierla pack no presente (SKIP soft)</p>'}
    </div>
  </section>

  <section class="block open pitch-keep" id="sec-guion">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3 id="guion">Guion interactivo 12 min</h3><span>▾</span></div>
    <div class="sec-body">
      <div class="guion-controls">
        <button type="button" class="btn primary" id="guion-start">Iniciar</button>
        <button type="button" class="btn" id="guion-next">Siguiente paso</button>
        <button type="button" class="btn ghost" id="guion-reset">Reset</button>
        <span class="muted" id="guion-status" aria-live="polite">Paso 0 / 5</span>
      </div>
      <div class="guion-step" data-step="0" data-panel="" tabindex="0">0:00 — Gancho: tres contratos, un criterio de calidad; HOLD es feature.</div>
      <div class="guion-step" data-step="1" data-panel="tobarra" tabindex="0">1–4 min — <b>Tobarra OPS</b>: LWIR + {tb_guion}. ROS multi-estimador. Sin este material no inventamos el número.</div>
      <div class="guion-step" data-step="2" data-panel="nijar" tabindex="0">4–7 min — <b>Níjar AND</b>: perímetro REDIAM ~{ha_nj} ha · verdict {_esc(nj.get("verdict"))} · decisión {_esc(nj.get("decision_open"))}. FIRMS+dNBR cuando hay.</div>
      <div class="guion-step" data-step="3" data-panel="camino" tabindex="0">7–10 min — <b>Caminomorisco EXT</b>: perímetro RAI ~{ha_cm} ha · det {_esc((cm.get("key_numbers") or {}).get("fecha_det"))} → {_esc((cm.get("key_numbers") or {}).get("fecha_ext"))}. PARTIAL si FIRMS SKIP — no inventamos hotspots.</div>
      <div class="guion-step" data-step="4" data-panel="" tabindex="0">10–12 min — Síntesis dual + ask: 30 min feedback / ancla Vp-ha / carta interés.</div>
    </div>
  </section>

  <section class="block open pitch-keep" id="pitch" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Pitch 60 s + reliability story</h3><span>▾</span></div>
    <div class="sec-body">
      <p><b>Qué vendemos:</b> Fire Decision posture (GO/HOLD/ABSTAIN), multi-CCAA proof, scoreboard industrial, audit trail.</p>
      <p><b>Por qué HOLD vende:</b> el sistema se niega a recomendar cuando faltan fuentes — residual silent-GO controlado por diseño (suite de abstención/gates; target contractual ≤ 1×10⁻⁶ silent-GO bajo tests), no “mapa optimista”.</p>
      <p><b>Audit trail:</b> hash de inputs/outputs cuando hay decide API · actas E2E GOLD/AND/EXT · provenance de cada pack · timestamps UTC en footer.</p>
      <p><b>Números de esta demo:</b> Tobarra {vp_tb} m/min · {ha_tb} ha · Níjar {ha_nj} ha O2 · Camino {ha_cm} ha O2 · catálogo AND {_esc(kpi.get("n_and_catalog", "—"))} IF.</p>
      <p class="muted">Print (botón) o <a href="export/pitch_onepager.html">export/pitch_onepager.html</a> · markdown en export/pitch_onepager.md</p>
    </div>
  </section>

  <section class="block open" id="provenance" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Provenance · contactos fuente</h3><span>▾</span></div>
    <div class="sec-body">
      <table class="grid">
        <thead><tr><th>Fuente</th><th>Contacto / buzón</th><th>Rol en demo</th></tr></thead>
        <tbody>{prov_rows}</tbody>
      </table>
      <p class="muted" style="font-size:.8rem;margin:.5rem 0 0">{_esc(provenance.get("note") or "Atribuciones siempre visibles. No se inventan Vp/ha.")}
        · Producto: <a href="mailto:{_esc(provenance.get("product_contact") or "alonso.alvbal@gmail.com")}">{_esc(provenance.get("product_contact") or "alonso.alvbal@gmail.com")}</a>
        · Build UTC: {built}</p>
    </div>
  </section>

  <section class="block open pitch-keep" id="sell" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="true"><h3>Sell kit · CTAs</h3><span>▾</span></div>
    <div class="sec-body">
      <div class="cta-box">
        <div class="cta-card">
          <h4>Feedback 30 min</h4>
          <p>End-user o partner: ¿se entiende? ¿qué faltaría en sala?</p>
          <a class="btn primary" href="mailto:alonso.alvbal@gmail.com?subject=WFD%20feedback%2030%20min">Escribir</a>
        </div>
        <div class="cta-card">
          <h4>Ancla Vp/ha (1 IF)</h4>
          <p>ASEMA / RAI / INFOCAM: un incendio con ha y Vp eleva OPEN a O1.</p>
          <a class="btn ops" href="mailto:alonso.alvbal@gmail.com?subject=WFD%20solicitud%20ancla%20IF">Solicitar</a>
        </div>
        <div class="cta-card">
          <h4>Carta de interés UE</h4>
          <p>UCPM / SUDOE / Horizon: living demo multi-region ES.</p>
          <a class="btn" href="mailto:alonso.alvbal@gmail.com?subject=WFD%20carta%20interes%20UE">Contactar</a>
        </div>
        <div class="cta-card">
          <h4>Más producto</h4>
          <p>Sala de mando · Metrics hub · Decide API local.</p>
          <a class="btn ghost" href="{_esc(_safe_href(manifest.get("commander_href")) or "../../docs/commander/index.html")}">Commander</a>
          <a class="btn ghost" href="{_esc(_safe_href(manifest.get("portal_href")) or "../../docs/PORTAL.html")}">Portal</a>
        </div>
      </div>
    </div>
  </section>

  <section class="block" id="honest" tabindex="-1">
    <div class="sec-head" data-toggle role="button" tabindex="0" aria-expanded="false"><h3>Honestidad · Q&amp;A</h3><span>▾</span></div>
    <div class="sec-body">
      <div class="honesty-banner" role="note" style="background:rgba(47,212,200,.10);border-color:rgba(47,212,200,.45);color:#b8f0ea">
        <strong>ML-first (U1 TEST honest):</strong>
        mean IoU eval ~<b>0.86</b> · selective@80 ~<b>0.90</b> · ECE ~<b>0.15</b>.
        Catalog holdout <b>0.8963</b> = provenance only — <em>not</em> live fire certainty, not ops ROS.
        Live ML → Card HOLD/ABSTAIN when unreliable · <code>field_ops</code> fusion OFF ·
        refs: <code>docs/ML_PRODUCT_SCORECARD.json</code>, <code>docs/ML_U1_PROMOTE_RECORD.json</code>.
      </div>
      <ul>
        <li>No inventamos Vp/ha · hull FIRMS ≠ quemado oficial</li>
        <li>HOLD/ABSTAIN sin ancla ops · no despacho táctico</li>
        <li>Atribuciones: INFOCAM · REDIAM Junta Andalucía · RAI/INFOEX Junta Extremadura</li>
        <li><b>¿Por qué PARTIAL EXT?</b> O2 RAI PASS; archive FIRMS Spain 2025 no publicado (404) → SKIP satélite, no hotspots inventados.</li>
        <li><b>¿Sustituís INFOCA?</b> No. Validación y apoyo a la decisión.</li>
        <li><b>Reliability:</b> residual silent-GO mitigado por gates + ABSTAIN/HOLD; ver ONEPAGER comercial.</li>
        <li><b>ML live demo:</b> <code>python scripts/run_ml_live_card_demo.py --mode offline</code> → Decision Card + abstain/ECE note.</li>
      </ul>
    </div>
  </section>
  </main>

  <footer class="footer">
    Built {built} · demo_version {_esc(version)} · git {git_label} · schema {_esc(manifest.get("schema"))}<br/>
    Contacto: <a href="mailto:alonso.alvbal@gmail.com">alonso.alvbal@gmail.com</a> ·
    Plan: <a href="{_esc(_safe_href(manifest.get("plan_href")) or "../../docs/design/DEMO_MULTI_CCAA_TOBARRA_NIJAR_CAMINOMORISCO.md")}">demo multi-CCAA</a> ·
    <a href="export/pitch_onepager.html">pitch HTML</a>
  </footer>
</div>

<script id="perimeter-data" type="application/json">{perim_json}</script>
<script id="i18n-data" type="application/json">{i18n_json}</script>
<script>
(function(){{
  const params = new URLSearchParams(location.search);
  const panel = params.get('panel');
  const mode = params.get('mode') || 'full';
  document.body.classList.add('mode-' + mode);

  const SITE_PANELS = {{tobarra:1, nijar:1, camino:1}};
  function highlight(p) {{
    if (!p || !SITE_PANELS[p]) return;
    document.querySelectorAll('.site-card').forEach(c => {{
      c.classList.toggle('highlight', c.dataset.panel === p);
    }});
    const el = document.getElementById('card-' + p);
    if (el) el.scrollIntoView({{behavior:'smooth', block:'center'}});
  }}
  function openSection(id) {{
    const sec = document.getElementById(id);
    if (!sec) return;
    sec.classList.add('open');
    const head = sec.querySelector('[data-toggle]');
    if (head) head.setAttribute('aria-expanded', 'true');
    sec.scrollIntoView({{behavior:'smooth', block:'start'}});
  }}
  if (panel === 'decision') {{
    openSection('decision');
  }} else if (panel && SITE_PANELS[panel]) {{
    highlight(panel);
  }}
  // unknown panels: no tobarra false-positive highlight

  function toggleSec(h) {{
    const sec = h.parentElement;
    sec.classList.toggle('open');
    h.setAttribute('aria-expanded', sec.classList.contains('open') ? 'true' : 'false');
  }}
  document.querySelectorAll('[data-toggle]').forEach(h => {{
    h.addEventListener('click', () => toggleSec(h));
    h.addEventListener('keydown', (e) => {{
      if (e.key === 'Enter' || e.key === ' ') {{ e.preventDefault(); toggleSec(h); }}
    }});
  }});

  // Maps (lazy-ish: only when Leaflet present; OSM tiles optional offline)
  let perims = {{}};
  try {{ perims = JSON.parse(document.getElementById('perimeter-data').textContent || '{{}}'); }} catch (e) {{}}
  function drawMap(id, gj) {{
    const div = document.getElementById('map-' + id);
    if (!div || typeof L === 'undefined' || !gj) return;
    const map = L.map(div, {{ zoomControl: false, attributionControl: true }});
    L.tileLayer('https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png', {{
      maxZoom: 16, attribution: '&copy; OSM'
    }}).addTo(map);
    const layer = L.geoJSON(gj, {{
      style: {{ color: id === 'tobarra' ? '#f0a030' : '#e74c3c', weight: 2, fillOpacity: 0.25 }}
    }}).addTo(map);
    try {{ map.fitBounds(layer.getBounds().pad(0.12)); }} catch (e) {{
      map.setView([40.0, -3.5], 5);
    }}
    setTimeout(() => map.invalidateSize(), 200);
  }}
  ['nijar','camino','tobarra'].forEach(id => drawMap(id, perims[id]));

  // Guion
  let step = 0;
  const steps = document.querySelectorAll('.guion-step');
  function setStep(n) {{
    step = Math.max(0, Math.min(n, steps.length - 1));
    steps.forEach(s => s.classList.toggle('active', Number(s.dataset.step) === step));
    document.getElementById('guion-status').textContent = 'Paso ' + step + ' / ' + (steps.length - 1);
    const p = steps[step] && steps[step].dataset.panel;
    document.querySelectorAll('.site-card').forEach(c => {{
      if (c.dataset.optional === '1') return;
      if (!p) {{ c.classList.remove('dim','highlight'); return; }}
      const on = c.dataset.panel === p;
      c.classList.toggle('highlight', on);
      c.classList.toggle('dim', !on);
    }});
  }}
  document.getElementById('guion-start').onclick = () => {{ setStep(0); document.getElementById('sec-guion').classList.add('open'); }};
  document.getElementById('guion-next').onclick = () => setStep(step + 1);
  document.getElementById('guion-reset').onclick = () => {{
    setStep(0);
    document.querySelectorAll('.site-card').forEach(c => c.classList.remove('dim','highlight'));
  }};

  // What-if
  document.getElementById('whatif-no-anchor').addEventListener('change', (e) => {{
    const on = e.target.checked;
    const card = document.getElementById('card-tobarra');
    if (!card) return;
    const pill = card.querySelectorAll('.pill')[1];
    if (pill) pill.textContent = on ? 'decisión: HOLD (simulado sin ancla)' : 'decisión: {_esc(tb.get("decision_open"))}';
    if (on) card.classList.add('highlight');
  }});

  // Modes
  function setMode(m) {{
    document.body.classList.remove('mode-full','mode-pitch','mode-guion');
    document.body.classList.add('mode-' + m);
    ['full','pitch','guion'].forEach(x => {{
      const b = document.getElementById('btn-mode-' + x);
      if (b) b.setAttribute('aria-pressed', x === m ? 'true' : 'false');
    }});
    const u = new URL(location.href);
    u.searchParams.set('mode', m);
    history.replaceState(null, '', u);
  }}
  document.getElementById('btn-mode-full').onclick = () => setMode('full');
  document.getElementById('btn-mode-pitch').onclick = () => setMode('pitch');
  document.getElementById('btn-mode-guion').onclick = () => {{ setMode('guion'); document.getElementById('sec-guion').classList.add('open'); }};

  // i18n
  let lang = 'es';
  const i18n = JSON.parse(document.getElementById('i18n-data').textContent || '{{}}');
  function applyLang() {{
    document.getElementById('btn-lang').textContent = lang.toUpperCase();
    document.documentElement.lang = lang;
    const ht = document.getElementById('hero-title');
    const hs = document.getElementById('hero-sub');
    if (ht && i18n.hero_title) ht.textContent = i18n.hero_title[lang];
    if (hs && i18n.hero_sub) hs.innerHTML = i18n.hero_sub[lang];
    document.querySelectorAll('[data-es][data-en]').forEach(el => {{
      el.textContent = el.getAttribute('data-' + lang) || el.textContent;
    }});
  }}
  document.getElementById('btn-lang').onclick = () => {{
    lang = lang === 'es' ? 'en' : 'es';
    applyLang();
  }};

  document.getElementById('btn-print').onclick = () => window.print();

  // Keyboard: 1/2/3 sites, G guion, P pitch, L lang
  document.addEventListener('keydown', (e) => {{
    if (e.target && (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA' || e.target.isContentEditable)) return;
    const k = e.key;
    if (k === '1') highlight('tobarra');
    else if (k === '2') highlight('nijar');
    else if (k === '3') highlight('camino');
    else if (k === 'g' || k === 'G') {{ setMode('guion'); document.getElementById('sec-guion').classList.add('open'); document.getElementById('guion').scrollIntoView({{behavior:'smooth'}}); }}
    else if (k === 'p' || k === 'P') {{ setMode('pitch'); }}
    else if (k === 'l' || k === 'L') {{ lang = lang === 'es' ? 'en' : 'es'; applyLang(); }}
  }});
}})();
</script>
</body>
</html>
"""
