"""Run the complete data-validation sprint for the semireal candidate."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


DEFAULT_DATASET_ID = "semireal_controlled_001"


def run(command: list[str]) -> None:
    print(" ".join(command), flush=True)
    subprocess.run(command, check=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run the full data-validation sprint.")
    parser.add_argument("--dataset-id", default=DEFAULT_DATASET_ID)
    parser.add_argument("--skip-tests", action="store_true")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    python = sys.executable
    dataset_id = args.dataset_id
    dataset_dir = Path("data") / "candidates" / dataset_id
    audit_dir = Path("outputs") / f"{dataset_id}-audit"
    pipeline_dir = Path("outputs") / dataset_id
    audit_doc = Path("docs") / f"REAL_SEQUENCE_AUDIT_{dataset_id}.md"

    if dataset_id != DEFAULT_DATASET_ID:
        raise SystemExit("only semireal_controlled_001 is generated by this sprint script for now")

    run([python, "scripts/generate_semireal_candidate.py"])
    run(
        [
            python,
            "scripts/audit_dataset_candidate.py",
            "--images",
            str(dataset_dir / "images"),
            "--masks",
            str(dataset_dir / "masks"),
            "--annotations",
            str(dataset_dir / "annotations"),
            "--output",
            str(audit_dir),
            "--markdown-output",
            str(audit_doc),
            "--event-id",
            dataset_id,
            "--sensor-id",
            "thermal_semireal",
            "--estimated-error-m",
            "2.0",
        ]
    )
    run(
        [
            python,
            "-m",
            "wildfire_front",
            "ingest-geotiff",
            "--images",
            str(dataset_dir / "images"),
            "--masks",
            str(dataset_dir / "masks"),
            "--output",
            str(pipeline_dir),
            "--event-id",
            dataset_id,
            "--sensor-id",
            "thermal_semireal",
            "--estimated-error-m",
            "2.0",
        ]
    )
    run(
        [
            python,
            "scripts/verify_data_validation_milestone.py",
            "--dataset-dir",
            str(dataset_dir),
            "--audit-dir",
            str(audit_dir),
            "--pipeline-dir",
            str(pipeline_dir),
            "--audit-doc",
            str(audit_doc),
            "--json-output",
            str(audit_dir / "milestone_verification.json"),
        ]
    )
    if not args.skip_tests:
        run([python, "-m", "unittest", "discover", "-s", "tests", "-v"])


if __name__ == "__main__":
    main()
